### 0. 커넥터 생성
POST localhost:8083/connectors
Content-Type: application/json

{
  "name": "example-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "db-mysql",
    "database.port": "3306",
    "database.user": "root",
    "database.server.id": "100000",
    "database.server.name": "example_server",
    "topic.prefix" : "example-",
    "tasks.max" : "1",
    "database.include.list": "example",
    "table.include.list": "example.member",
    "database.allowPublicKeyRetrieval":"true",
    "database.history.kafka.bootstrap.servers": "kafka:9092",
    "database.history.kafka.topic": "example-history-topic",
    "schema.history.internal.kafka.bootstrap.servers" : "kafka:9092",
    "schema.history.internal.kafka.topic": "example-history-topic",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.converter.schemas.enable": "false",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "include.schema.changes": "false",
    "snapshot.mode": "schema_only",
    "decimal.handling.mode": "string",
    "snapshot.locking.mode": "none",
    "transforms": "Reroute",
    "transforms.Reroute.type": "io.debezium.transforms.ByLogicalTableRouter",
    "transforms.Reroute.topic.regex": "(.*)(example).(.*)",
    "transforms.Reroute.topic.replacement": "db_example_$3"
  }
}

### 1-1. 커넥터 조회
GET localhost:8083/connectors
Content-Type: application/json

### 1-2. 커넥터 상태 조회
GET localhost:8083/connectors/example-connector/status
Content-Type: application/json

// 토픽 이름
// example-history-topic
// db_example_member

### 2. 회원 생성
POST localhost:9090/v1/members/create
Content-Type: application/json

{
  "name": "yanglet",
  "age": 26
}

### 3. 회원 조회
GET localhost:9090/v1/members/1
Content-Type: application/json

### 4. 회원 수정
PUT localhost:9090/v1/members/1
Content-Type: application/json

{
  "name": "yanglet_update",
  "age": 27
}

### 5. 회원 삭제
DELETE localhost:9090/v1/members/1
Content-Type: application/json
